### PR TITLE
Update for Dalamud apiX and Dawntrail

### PR DESCRIPTION
**Pull request by Xpahtalo**
Just a quick update to the new API level so I could what progress you had already made.

### CODE REVIEW

**Comment by MikeMatrix** [comment]
Seems to compile fine, with the only exception that for some reason, trying to restore your PR on my machine made it spit out a bunch of `The package is different than the last restore.`.
Had to update from my side so the `contentHash` fields matched again for my machine. You have any idea why that would behave like that?

**Comment by Xpahtalo** [comment]
Restore will complain if the local versions don't exactly match what's in the lock file, but it won't download the the specified versions unless explicitly instructed to. Should build now.

**Comment by MikeMatrix** [comment]
I got raid tonight, but I will check it as soon as I can

**Comment by MikeMatrix** [comment]
LGTM

**Pull request merged**
